name: Run Actions with a Schedule
on:
  schedule:
    # Use https://crontab.guru to find the syntax for your desired schedule
    # By default, run daily at 00:00
    - cron: '0 0 * * *'
  workflow_dispatch:
    # This allows you to run the action manually
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install node
        uses: actions/setup-node@v3
        with:
          # Use the node version specified in .nvmrc
          node-version-file: '.nvmrc'
          # Alternatively, you can comment out the previous line, and use
          # node-version: current
      - name: Install dependencies
        run: npm install
      - name: Run default node task
        run: npm start
